---
all:
  hosts:
    mail.ovirt.org:
    ovirt-web-builder.osci.io:
    www.phx.ovirt.org:

  children:
    phx_zone:
     hosts:
       www.phx.ovirt.org:

    # zone managed by OSAS in the Community Cage project
    osci_zone:
      hosts:
        ovirt-web-builder.osci.io:
        mail.ovirt.org:

    mailing:
      hosts:
        mail.ovirt.org:

    web_builders:
      hosts:
        ovirt-web-builder.osci.io:

