---
all:
  hosts:
    mail.ovirt.org:
    monitoring.ovirt.org:
      # TODO: remove when DNS is switched
      ansible_host: 8.43.85.199
    ovirt-web-builder.int.osci.io:
      ansible_python_interpreter: /usr/bin/python3
    www.ovirt.org:
      # TODO: remove when DNS is switched
      ansible_host: 8.43.85.224
    glance.ovirt.org:
      # TODO: remove when DNS is switched
      ansible_host: 8.43.85.218

  children:
    phx_zone:
      hosts: {}

    # zone managed by OSAS in the Community Cage project
    osci_zone:
      hosts:
        mail.ovirt.org:
        monitoring.ovirt.org:
        www.ovirt.org:
        glance.ovirt.org:
      vars:
        nameservers: "{{ osci.dns }}"
        mail_forwarder: "{{ osci.mail_forwarder }}"
      children:
        osci_internal_zone:
          hosts:
            ovirt-web-builder.int.osci.io:

    mailing:
      hosts:
        mail.ovirt.org:

    web_builders:
      hosts:
        ovirt-web-builder.int.osci.io:

    dns_servers:

    jenkins_masters:
      hosts:
        jenkins-staging.ovirt.org:
        jenkins.ovirt.org:

