---
- src: git+https://github.com/OSAS/ansible-role-selinux.git
  name: selinux
- src: git+https://github.com/OSAS/ansible-role-openssh.git
  name: openssh
- src: git+https://gitlab.com/osas/ansible-role-entropy.git
  name: entropy
- src: git+https://gitlab.com/osas/ansible-role-guest_virt_tools.git
  name: guest_virt_tools
- src: git+https://gitlab.com/osas/ansible-role-memcached.git
  name: memcached
- src: git+https://gitlab.com/osas/ansible-role-postgresql.git
  name: postgresql
- src: git+https://gitlab.com/osas/ansible-role-mailman3.git
  name: mailman3
- src: git+https://gitlab.com/osas/ansible-role-postgrey.git
  name: postgrey
- src: git+https://gitlab.com/osas/ansible-role-postfix.git
  name: postfix
- src: git+https://gitlab.com/osas/ansible-role-spamassassin.git
  name: spamassassin
- src: git+https://gitlab.com/osas/ansible-role-dovecot.git
  name: dovecot
- src: git+https://gitlab.com/osas/ansible-role-ah-httpd.git
  name: httpd
- src: git+https://vcs-git.duckcorp.org/duckcorp/ansible-role-httpd_php_fpm
  name: httpd_php_fpm
- src: git+https://gitlab.com/osci/ansible-role-web_builder.git
  name: builder
- src: git+https://gitlab.com/osas/ansible-role-msmtp.git
  name: msmtp
- src: git+https://gitlab.com/osas/ansible-role-unattended_updates.git
  name: unattended_updates
- src: git+https://gitlab.com/osas/ansible-role-tor.git
  name: tor
- src: git+https://gitlab.com/osas/ansible-role-mailing-lists-server.git
  name: mailing-lists-server
- src: git+https://gitlab.com/osas/ansible-role-chrony.git
  name: chrony
- src: https://github.com/OSAS/ansible-role-swap_file
  name: swap_file
- src: git+https://gitlab.com/osas/ansible-role-httpd_wsgi.git
  name: httpd_wsgi
- src: git+https://gitlab.com/osas/ansible-role-data_movebind.git
  name: data_movebind
- src: git+https://gitlab.com/OSAS/ansible-role-lvm_partition.git
  name: lvm_partition
