---
- name: install root ssh keys
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
  - misc_main.pub
  - misc_backup.pub
  - duck.pub
  - eedri.pub
  - ena.pub
  - ederevea.pub
  - bkorren.pub
  - amarchuk.pub
  - grosenth.pub
  - eyonasi.pub
  - krrai.pub
  - dvolkov.pub

- name: Remove old root ssh keys
  authorized_key:
    user: root
    state: absent
    key: "{{ item }}"
  with_file:
    - misc_nano_old.pub
    - misc_tpm_old.pub
    - quaid.pub
    - szidmi.pub

