#!/bin/bash
# {{ ansible_managed }}
set -e

case $RENEWED_DOMAINS in
    mx*|mail*|lists*)
        # also reload httpd as we use a shared cert
        systemctl reload postfix dovecot httpd
        ;;
    *)
        systemctl reload httpd
        ;;
esac

