---

- hosts: mail.ovirt.org
  vars:
    vg_name: "data"
    ml_lv_name: "mailman"
    fs_type: xfs
  tasks:

    - name: Add swap file
      include_role:
        name: swap_file
      vars:
        size: 1G
        path: /var/swap

    - name: Test if partition for extra data exists
      stat:
        path: /dev/vdb1
      register: data_1

    - name: Partition disk for extra data
      parted:
        device: /dev/vdb
        label: gpt
        number: 1
        name: "data_1"
        flags: [ lvm ]
        state: present
      when: not data_1.stat.exists

    - name: Create LVM VG for extra data
      lvg:
        vg: "{{ vg_name }}"
        pvs: "/dev/vdb1"
        state: present

    # if we need more, adding a new PV in the VG would be very easy
    - name: Create LVM LV for Mailing-Lists data
      lvol:
        lv: "{{ ml_lv_name }}"
        vg: "{{ vg_name }}"
        size: "100%VG"
        state: present

    - name: Create filesystem for Mailing-Lists data
      filesystem:
        fstype: "{{ fs_type }}"
        dev: "/dev/{{ vg_name }}/{{ ml_lv_name }}"

    - name: Mount filesystem for Mailing-Lists data
      mount:
        src: "/dev/{{ vg_name }}/{{ ml_lv_name }}"
        path: /srv/data
        fstype: "{{ fs_type }}"
        state: mounted

  tags: partitioning


# use inventory_hostname or webui_vhost as hostname for MX and IMAP (TLS SAN OK)
- hosts: mail.ovirt.org
  vars:
    webui_vhost: lists.ovirt.org
    # due to https://github.com/ansible/ansible/issues/21890
    sa_config_bits: /etc/mail/spamassassin/local.cf.d
  tasks:

    - name: Install Mailing-Lists Server
      include_role:
        name: mailing-lists-server
        public: yes
        apply:
          tags: ml_install_core
      vars:
        display_name: "oVirt List Archives"
        domain: "{{ ovirt_domain }}"
        admin_users:
          - duck
          - misc
          - doronf
          - didi
          - dvolkov
        mail_aliases:
          # Person who should get root's mail
          root: "{{ ['root'] + ovirt_infra_emails }}"
          listmaster: root
          www: webmaster
          webmaster: root
          noc: root
          hostmaster: root
          info: postmaster
          sales: postmaster
          # trap decode to catch security attacks
          decode: root
          contact: "{{ ovirt_infra_ml_pv }}"
          # aliases that jira would use
          infra-support: jira
          community: "{{ ovirt_community_emails }}"
          ## Random new aliases we create
          wordpress: community
          twitter: community
          identica: community
          eventbrite: community
          ovirtbot: "{{ eedri_mail }}"
          kerri: "{{ kerri_mail }}"
          pr: "{{ ovirt_press_emails }}"
          press: "{{ ovirt_press_emails }}"
          hootsuite: "{{ eedri_mail }}"
          quaid: "{{ quaid_mail }}"
          events: community
          ovirt-copr: "{{ eedri_mail }}"
          infra-twitter: infra-private
          privacy: infra-private
          kubevirt-ci: infra-private
          # default assignee in bugzilla, no reply expected
          bugs: /dev/null
          # email used by Zuul, we don't need the replies
          zuul: /dev/null
        use_simple_tls: True
        with_dovecot: True
        with_pop3: true
        # social_auth is defined in host_vars
        # caught by underlying 'mailman3' role
        with_fedora_auth: True
        # caught by underlying 'postgrey' role
        whitelist_clients:
          - gerrit.ovirt.org
          - redhat.com
        # caught by underlying 'postfix' role
        myorigin: "{{ ovirt_domain }}"
        mynetworks:
          - 66.187.230.42
          - 169.62.7.160/27
          - 2607:f0d0:3a01:121::/64
        local_accounts:
          - jira
          - jenkins
        use_custom_favicon: True
        # TODD: workaround Django vhost filtering not working well
        multi_domains: false
      tags: ml_install_core

    - name: Configure web access to old ML archives
      copy:
        src: "mailing/web/old_ml_archives.conf"
        # Duck: we should think about making _vhost_confdir part of the public API
        dest: "{{ _vhost_confdir }}/"
        owner: root
        group: root
        mode: 0644
      notify: reload httpd

    - name: "Create Mail Templates directories"
      file:
        path: "/var/lib/mailman3/templates/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      loop:
        - site/en

    - name: "Install Mail Templates"
      copy:
        src: "mailing/mail_templates/{{ item }}"
        dest: "/var/lib/mailman3/templates/{{ item }}"
        owner: root
        group: root
        mode: 0644
      loop:
        - "site/en/list:member:regular:footer.txt"
        - "site/en/list:member:digest:footer.txt"

    - name: Install custom favicon
      copy:
        src: "mailing/web/{{ item }}"
        dest: "{{ webapp_path }}/static-extra/"
        owner: root
        group: root
        mode: 0644
      loop:
        - favicon.ico
        - ovirt_logo.png
      notify: Update static files

    - name: Install custom branded navbar template
      copy:
        src: "mailing/web/navbar-brand.html"
        dest: "{{ webapp_path }}/templates/hyperkitty/"
        owner: root
        group: root
        mode: 0644
      notify: reload apache
    # quick fix for SPAM generating a low Spamassassin score

    - name: SPAM filtering
      copy:
        src: "mailing/sa_ovirt_mls.cf"
        dest: "{{ sa_config_bits }}/10_ovirt_mls.cf"
        owner: root
        group: root
        mode: 0644
      notify: regenerate spamassassin configuration

    - name: Discard very-likely SPAM
      blockinfile:
        path: /etc/postfix/header_checks
        block: |
          /^X-Spam-Level: \*{8,}/ DISCARD
        marker: "# {mark} ANSIBLE MANAGED BLOCK ML-SPAM"
      notify: reload mail system

  tags: ml_install


- hosts: mail.ovirt.org
  tasks:

    - name: install Dovecot users
      copy:
        src: mailing/users/
        dest: /etc/dovecot/users/
        owner: root
        group: dovecot-proxy
        mode: 0640

    - name: Auto-expire Jenkins mailbox
      cron:
        name: "Auto-expire Jenkins mailbox"
        minute: "21"
        hour: "6"
        user: root
        job: "doveadm expunge -u jenkins mailbox Inbox savedbefore 30d"

  tags: mail_boxes


- hosts: mail.ovirt.org
  tasks:

    - name: use the second disk for all Mailman3 data
      include_role:
        name: data_movebind
      vars:
        src: /var/lib/mailman3
        dest: /srv/data/mailman3-lib
        services:
          - crond
          - mailman3
          - httpd

    - name: use the second disk for all Hyperkitty+Postorius data
      include_role:
        name: data_movebind
      vars:
        src: /var/www/mailman
        dest: /srv/data/mailman3-www
        services:
          - crond
          - mailman3
          - httpd

  tags: ml_storage

